config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'top#index'
  resources :mates, only:[:index, :show]
  resources :messages, only: [:index]
  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create]
  resources :rooms, only: [:new, :create] do
    resources :messages, only: [:index, :create]
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
 after_create_commit { MessageBroadcastJob.perform_later self }
  
  belongs_to :room
  belongs_to :user

  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room, dependent: :destroy
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :room_users
         has_many :rooms, through: :room_users, dependent: :destroy
         has_many :messages, dependent: :destroy
         has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :following, through: :active_relationships
         
         mount_uploader :image, ImageUploader
         validates :image, presence: true
         
         validates :last_name, presence: true
         validates :first_name, presence: true
         validates :self_introduction, presence: true, length: { maximum: 1000 }

         def following?(other_user)
          following.include?(other_user)
        end

        def self.guest
          find_or_create_by!(email: 'test@testtest9.com') do |user|
            user.password = SecureRandom.urlsafe_base64
            user.password_confirmation = user.password
            user.last_name = 'yamada'
            user.first_name = 'taro'
            user.self_introduction = 'Hello'
            user.image = 'mate-pic2.jpg'
         end
      end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:/]
  before_action :configure_permitted_parameters, if: :devise_controller?
 

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :self_introduction, :image])
  end
end

app/controllers/mates_controller.rb
class MatesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
protect_from_forgery prepend: true

  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast 'message_channel', content: @message
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:message).merge(user_id: current_user.id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.active_relationships.create(create_params)
  end

  private

  def create_params
    params.require(:relationship).permit(:following_id).merge(follower_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_messages_path(@room.id)
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all.order('created_at DESC')
   
  end

  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new
  end

  def edit
  end

  def update
    current_user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :encrypted_password, :self_introduction, :image)
  end
end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mates_helper.rb
module MatesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mates/index.html.erb
<h1>Mates#index</h1>
<p>Find me in app/views/mates/index.html.erb</p>

app/views/mates/show.html.erb
<%# Mateの概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
     
     <% if @item.order.present? %> 
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
     <% end %>
      
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @item.price %>
      </span>
      <span class="item-postage">
        <%= @item.shipping_fee.name %>
      </span>
    </div>

   
   <% if user_signed_in? && @item.order.blank? %>
   <% if current_user.id == @item.user_id %>
      <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
   <% else %>
     <%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-red-btn"%>
   <% end %>
  <% end %>
   

    <div class="item-explain-box">
      <span><%= @item.item_info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.schedule.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /Mateの概要 %>

app/views/messages/_main_chat.html.erb
<div class="messages">
 <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :message, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">image</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit 'Send', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.last_name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
       <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.message %>
    </div>
    <i class="fas fa-phone fa-3x"></i>
  </div>
</div>

app/views/messages/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.webrtc.ecl.ntt.com/skyway-4.4.0.js"></script>
  <script src="https://kit.fontawesome.com/e9c541a354.js" crossorigin="anonymous"></script>
  <title>SkyWay</title>
</head>

<body>
<div class="wrapper">


<div class="video">
<video id="my-video" width="400px" autoplay muted playsinline></video>
<p id="my-id"></p>
<textarea id="their-id"></textarea>
  <button id="make-call">発信</button>
  <video id="their-video" width="400px" autoplay muted playsinline></video>
</div>
 
 <script>
  let localStream;

  // カメラ映像取得
  navigator.mediaDevices.getUserMedia({video: true, audio: true})
    .then( stream => {
    // 成功時にvideo要素にカメラ映像をセットし、再生
    const videoElm = document.getElementById('my-video');
    videoElm.srcObject = stream;
    videoElm.play();
    // 着信時に相手にカメラ映像を返せるように、グローバル変数に保存しておく
    localStream = stream;
  }).catch( error => {
    // 失敗時にはエラーログを出力
    console.error('mediaDevice.getUserMedia() error:', error);
    return;
  });
</script>



 
  <div class="chat">
  <%= render "main_chat" %>
 </div>  
</div>

<%= javascript_pack_tag 'video' %>
</body>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>New Chat Room</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :Room_Name, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'Input room name'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>Chat Mate</label>
      </div>
      <div class='chat-room-form__field--right'>
       <select name="room[user_ids][]">
           <option value="">select your mate</option>
         <% User.where.not(id: current_user.id).each do |user| %>
           <option value=<%= user.id %>><%= user.last_name %></option>
          <% end %>
        </select>     
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/top/index.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
 <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="css/top.css"/>
   <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Cherry+Swash:700" rel="stylesheet">
    <title>Mate</title>
  </head>

<body>
<header class='top-page-header'>
  <div class='nav-left'>
    <ul class='lists-left'>
      <li><%= link_to 'Genre', "#", class: "category-list" %></li>
      <li><%= link_to 'Mate', users_path, class: "human-list" %></li>
    </ul>
  </div>
  <div class='nav-right'>  
    <ul class='lists-right'>   
     <% if user_signed_in? %>     
      <li><%= link_to current_user.last_name, "#", class: "user-last-name" %> </li> 
      <li><%= link_to 'Log-out', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <li><%= link_to 'Profile', edit_user_registration_path, class: "profile" %></li>
     <% else %> 
      <li><%= link_to 'Log-in', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'Sign-up', new_user_registration_path, class: "sign-up" %></li>
      <li><%= link_to 'Guest', users_guest_sign_in_path, method: :post, class: "login" %></li>
     <% end %>  
    </ul>
  </div>  
</header>

 <div class="contents">
   <div class="top-image">
    <%= image_tag asset_path("top-image4.jpeg", alt:"image1"), class:"top-image" %>
   <p>Find your Mate</p>
   <span>
   <%= link_to 'English', users_path, class: 'circle' %> 
   <%= link_to 'Programming', users_path, class: 'circle' %> 
   <%= link_to 'Chinese', users_path, class: 'circle' %> 
   </span>
   </div>
     
  
      <!-- 『Mate候補たち』を表示する -->
      <div class="bottom-content">
        <h2 class="heading-name">Recommend for you</h2>
        <ul class="mate-list">
          <li>
            <%= image_tag asset_path("mate-pic1.webp", alt:"mate1"), class:"mate-image" %>
            <h4 class="mate-name">kane</h4>
          </li>
          <li>
             <%= image_tag asset_path("mate-pic2.jpg", alt:"mate2"), class:"mate-image" %>
            <h4 class="mate-name">Mary</h4>
          </li>
          <li>
             <%= image_tag asset_path("mate-pic3.jpeg", alt:"mate3"), class:"mate-image" %>
            <h4 class="mate-name">Juliana</h4>
          </li>
        </ul>
      </div>
   </div>


    <div class='user-contents'>
    <h2 class='title'>Mate</h2>
   
    <ul class='user-lists'>
      <% @users.each do |user| %>
      <li class='list'>
        <%= link_to user_path(user.id) do %>
        <div class='user-img-content'>
           <% if user.image? %>   
            <%= image_tag user.image.url, class: "user-img" %>
           <% end %>
        </div>
        <div class='user-info'>
          <%= user.last_name %>
        </div>
       <% end %>
      </li>
     <% end %> 
   </div>  
  </div> 


<footer>
 <div class="logo">
  JE SUIS TOUJOURS A COTE DE VOUS
 </div>
 <ul class="nav">
        <li class="nav-nav">WORKS</li>
        <li class="nav-nav">BLOG</li>
        <li class="nav-nav">RECRUIT</li>
        <li class="nav-nav">COMPANY</li>
        <li class="nav-nav">CONTACT</li>
      </ul>
</footer>


</body>

 

app/views/users/_follow.html.erb
 <%= form_with model: relationship, remote: true do |f| %> 
    <div><%= f.hidden_field :following_id, value: @user.id %>
    <%= f.submit "LIKE", class: "btn btn-primary" %>  
    </div>
  <% end %>  

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<head>
    <meta charset="UTF-8">
    <title>ユーザー一覧</title>
    <link rel="stylesheet" href="userIndex.css">
</head>

<body>
<div class="main users-index">
  <div class="container">
   <h1 class="users-heading">User List</h1>

   <% @users.each do |user| %>
    <div class="users-index-item">
      <div class="user-right">
     <!-- 下記のコードでユーザーを表示 -->
     <div class="account-profile-image d-flex flex-column">  
       <% if user.image? %>      
       <%= image_tag user.image.url %>
      <% end %>
     </div>
     <div class="user-info"> 
      <%= link_to(user.last_name, user_path(user.id)) %>
      <%= link_to(user.first_name, user_path(user.id)) %>
      <%= link_to(user.self_introduction, user_path(user.id)) %>
    </div> 

    </div>
    </div>
  <% end %>

 </div>
</div>

</body>

app/views/users/show.html.erb
<head>
    <meta charset="UTF-8">
    <title>ユーザー詳細</title>
    <link rel="stylesheet" href="userShow.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
</head>

<body>
<div class="show-page">
 <div class="bg">
<div class="text-center">
    <%= image_tag @user.image.url, class: "image" %> 
</div>    
<div class="text-center" id = "user-description">
    <%= @user.last_name %> 
     <br><%= @user.self_introduction %><br>
     <% if user_signed_in? %> 
      <% if @user != current_user %>
       <div id="follow_form">
        <% if current_user.following?(@user) %> 
          <button id="liked.btn.btn-default">Liked</button>
        <% else %> 
         <%= render 'follow', {relationship: @relationship} %> 
        <% end %>
      </div> 
      <% end %>
     <% end %>  
     <div class="chat-room">
     <% unless @user.id == current_user.id %>
      <%= link_to("Start Chat", new_room_path) %>  
     <% end %>   
     </div>      
    </div>  
   </div>   
</div>
</div>




<script type="text/javascript" src="javascript/create.js.erb"></script>
</body>